# Use lightweight Nginx to serve React build
FROM nginx:stable-alpine

# Clean default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy the build folder generated by Jenkins into nginx
COPY build/ /usr/share/nginx/html/

# Expose default nginx port
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
